<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Bogus" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Fcg.Donations.Application\Fcg.Donations.Application.csproj" />
    <ProjectReference Include="..\..\src\Fcg.Donations.Domain\Fcg.Donations.Domain.csproj" />
    <ProjectReference Include="..\..\src\Fcg.Donations.Messages\Fcg.Donations.Messages.csproj" />
  </ItemGroup>
</Project>
