<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Bogus" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\fcs.Donations.Application\fcs.Donations.Application.csproj" />
    <ProjectReference Include="..\..\src\fcs.Donations.Domain\fcs.Donations.Domain.csproj" />
    <ProjectReference Include="..\..\src\fcs.Donations.Messages\fcs.Donations.Messages.csproj" />
  </ItemGroup>
</Project>
