<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Http" />
    <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
    <PackageReference Include="MediatR" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Http" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" />
    <PackageReference Include="Serilog.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Fcg.Donations.Application\Fcg.Donations.Application.csproj" />
    <ProjectReference Include="..\Fcg.Donations.Infrastructure.Http\Fcg.Donations.Infrastructure.Http.csproj" />
    <ProjectReference Include="..\Fcg.Donations.Infrastructure.Auth\Fcg.Donations.Infrastructure.Auth.csproj" />
    <ProjectReference Include="..\Fcg.Donations.Infrastructure.SqlServer\Fcg.Donations.Infrastructure.SqlServer.csproj" />
    <ProjectReference Include="..\Fcg.Donations.Infrastructure.MongoDb\Fcg.Donations.Infrastructure.MongoDb.csproj" />
    <ProjectReference Include="..\Fcg.Donations.Infrastructure.Kafka\Fcg.Donations.Infrastructure.Kafka.csproj" />
  </ItemGroup>
</Project>
