<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\fcs.Donations.Application\fcs.Donations.Application.csproj" />
  </ItemGroup>
</Project>
